### ISSUE TITLE
You should not be testing the View, you should only be testing the Model class

### ISSUE THREAD

**Issue by MohamedZalat** [xilingdc/3110ProjectRisk#16]

**Comment by MohamedZalat** [comment]
M3 - This is still an issue. Please fix it for the next milestone

**Comment by mralifahd** [comment]
What do you mean exactly by this? We aren't testing any view methods in the test. I only set the view in the begging of the test class because if I don't the model methods don't work. We need a view object because a lot of the methods from the model call view so I'm not sure how you want us to isolate view from the model class?

**Comment by MohamedZalat** [comment]
You cant have the view in your tests. If it is required it means your view and model are tightly coupled and you will lose design marks.

Your model should not have any dependency on the view.
________________________________
